language: python
os:
  - linux
  - osx
python:
  - 3.6
install:
  - pip install -r requirements.txt
script:
  - pwd
  - ls -a
  - pytest
  - pytest --cov
after_success:
  - codecov
env:
  - OANDA_TOKEN='test_environ_token'